export const layoutConstant = {
  topBarHeight: 40,
  headerHeight: 80,
  mobileNavHeight: 64,
  containerWidth: 1200,
  mobileHeaderHeight: 64,
  grocerySidenavWidth: 280,
};

export const keywords = [
  'hostel',
  'management',
  'platform',
  'hostel management',
  'hostel management platform',
  'hostel management system',
  'hostel management software',
  'hostel management app',
  'hostel management website',
];

export const hostelBedData = [
  { floor: 2, room: 201, bed_nos: ['A', 'B', 'C'] },
  { floor: 2, room: 202, bed_nos: ['A', 'B'] },
  { floor: 2, room: 203, bed_nos: ['A', 'B', 'C'] },
  { floor: 2, room: 204, bed_nos: ['A', 'B'] },
  { floor: 2, room: 205, bed_nos: ['A', 'B', 'C'] },
  {
    floor: 2,
    room: 206,
    bed_nos: ['A', 'B', 'C', 'D', 'E', 'F'],
  },
  { floor: 3, room: 301, bed_nos: ['A', 'B'] },
  { floor: 3, room: 302, bed_nos: ['A', 'B'] },
  { floor: 3, room: 303, bed_nos: ['A', 'B'] },
  { floor: 3, room: 304, bed_nos: ['A', 'B'] },
  { floor: 3, room: 305, bed_nos: ['A', 'B'] },
  { floor: 3, room: 306, bed_nos: ['A', 'B'] },
  { floor: 4, room: 401, bed_nos: ['A', 'B'] },
  { floor: 4, room: 402, bed_nos: ['A', 'B'] },
  { floor: 4, room: 403, bed_nos: ['A', 'B'] },
  { floor: 4, room: 404, bed_nos: ['A', 'B'] },
  { floor: 4, room: 405, bed_nos: ['A', 'B'] },
  { floor: 4, room: 406, bed_nos: ['A', 'B'] },
  { floor: 4, room: 407, bed_nos: ['A', 'B'] },
  { floor: 5, room: 501, bed_nos: ['A', 'B'] },
  { floor: 5, room: 502, bed_nos: ['A', 'B'] },
  { floor: 5, room: 503, bed_nos: ['A', 'B'] },
  { floor: 5, room: 504, bed_nos: ['A', 'B'] },
  { floor: 5, room: 505, bed_nos: ['A', 'B'] },
  { floor: 5, room: 506, bed_nos: ['A', 'B'] },
  { floor: 5, room: 507, bed_nos: ['A', 'B'] },
];
